[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/api/messages/health"
healthcheckTimeout = 100

[variables]
NODE_ENV = "production"
